BlackBox_TrackRoute_Application/Controllers/ManageTrucksController.cs
using BlackBox_TrackRoute_Application.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TrackRoute_Application.Core.DTO;
using TrackRoute_Application.Services.Implementation;
using TrackRoute_Application.Services.Interface;

namespace BlackBox_TrackRoute_Application.Controllers
{
    public class ManageTrucksController : Controller
    {
        private readonly ITruckService _truckService;
        public ManageTrucksController(ITruckService truckService)
        {
            _truckService = truckService;
        }
        [HttpGet]
        public IActionResult TruckDetails()
        {
            List< TruckDetailsViewModel> viewModelList = new List<TruckDetailsViewModel>();
            var Modeldto = _truckService.GetTruckData();
            if (Modeldto != null)
            {
                foreach (var dto in Modeldto)
                {
                    var vm = new TruckDetailsViewModel
                    {
                        TruckId = dto.TruckId,
                        TruckNumber = dto.TruckNumber,
                        Capacity = dto.Capacity,
                        StatusName = dto.StatusName,
                        CreatedBy = dto.CreatedBy,
                        ModelName = dto.ModelName,
                        UnitName = dto.UnitName
                    };
                    viewModelList.Add(vm);
                }
            }

            return View("~/Views/ManageTrucks/TruckDetails.cshtml", viewModelList);
        }
        public IActionResult EditTruck(int id)
        {
            TruckDetailsByIdViewModel viewModel = new TruckDetailsByIdViewModel();
            var dto = _truckService.GetTruckDataById(id);
            if (dto == null)
            {
                return NotFound();
            }
            viewModel = viewModel.MapToViewModel(dto);
            viewModel.btntext = "Update";
      
            return PartialView("~/Views/ManageTrucks/partialViews/_popupPartial.cshtml", viewModel);
        }
        public IActionResult CreateTruck()
        {
            var viewModel = new TruckDetailsByIdViewModel();
            viewModel.btntext = "Submit";
            return PartialView("~/Views/ManageTrucks/partialViews/_popupPartial.cshtml", viewModel);
        }
        [HttpPost]
        public IActionResult AddOrUpdateTruck(TruckDetailsByIdViewModel vm)
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            vm.UserId = Convert.ToInt32(userIdClaim.Value);

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            TruckDetailsById_dto dto = new TruckDetailsById_dto
            {
                TruckId = vm.TruckId,
                TruckNumber = vm.TruckNumber,
                ModelName = vm.ModelName,
                Capacity = vm.Capacity,
                UnitId = vm.UnitId,
                StatusId = vm.StatusId,
                UserId = vm.UserId
            };

            _truckService.CreateOrUpdateTruck(dto);

            return Json(new { success = true });
        }

    }


}

BlackBox_TrackRoute_Application/Views/ManageTrucks/partialViews/_popupPartial.cshtml
@* @model TruckDetailsByIdViewModel
<form id="editTruckForm" asp-controller="ManageTrucks" asp-action="AddOrUpdateTruck" method="post"> *@
@model TruckDetailsByIdViewModel
<form id="editLoadForm" asp-controller="ManageTrucks" method="post">

    <input type="hidden" asp-for="TruckId" />

    <div class="row mb-3">
        <div class="col-md-6">
            <label asp-for="TruckNumber" class="form-label"></label>
            <input asp-for="TruckNumber" class="form-control" />
            <span asp-validation-for="TruckNumber" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <label asp-for="ModelName" class="form-label"></label>
            <input asp-for="ModelName" class="form-control" />
            <span asp-validation-for="ModelName" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-6">
            <label asp-for="Capacity" class="form-label"></label>
            <input asp-for="Capacity" class="form-control" type="number" step="0.01" />
            <span asp-validation-for="Capacity" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <label asp-for="UnitId" class="form-label"></label>
            <select asp-for="UnitId" class="form-select">
                <option value="">-- Select Unit --</option>
                <option value="1">Kg</option>
                <option value="2">Ton</option>
                <option value="3">Pound</option>
                <option value="4">Gram</option>
                <option value="5">Ounce</option>
                <option value="6">Others</option>
            </select>
            <span asp-validation-for="UnitId" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-md-6">
            <label asp-for="StatusId" class="form-label"></label>
            <select asp-for="StatusId" class="form-select">
                <option value="">-- Select Status --</option>
                <option value="1">Available</option>
                <option value="2">Dispatched</option>
                <option value="3">Maintenance</option>
            </select>
            <span asp-validation-for="StatusId" class="text-danger"></span>
        </div>
      @*   <div class="col-md-6">
            <label asp-for="UserId" class="form-label"></label>
            <input asp-for="UserId" class="form-control" />
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div> *@
    </div>

    <div class="d-flex justify-content-end gap-2">
        <button type="submit" class="btn btn-primary">@Model.btntext</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
</form>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<style>
    .form-label {
        font-weight: 600;
        color: #0d6efd;
    }

    .row {
        margin-bottom: 1rem;
    }
</style>